# Generated by Django 5.0.7 on 2024-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_framework_urn_alter_loadedlibrary_urn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedcontrol',
            name='category',
            field=models.CharField(blank=True, choices=[('policy', 'Policy'), ('process', 'Process'), ('technical', 'Technical'), ('physical', 'Physical')], default='', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='csf_function',
            field=models.CharField(blank=True, choices=[('govern', 'Govern'), ('identify', 'Identify'), ('protect', 'Protect'), ('detect', 'Detect'), ('respond', 'Respond'), ('recover', 'Recover')], default='', max_length=20, verbose_name='CSF Function'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='effort',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='', help_text='Relative effort of the measure (using T-Shirt sizing)', max_length=2, verbose_name='Effort'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='link',
            field=models.CharField(blank=True, default='', help_text='External url for action follow-up (eg. Jira ticket)', max_length=1000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('active', 'Active'), ('inactive', 'Inactive')], default='', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('in_review', 'In review'), ('done', 'Done'), ('deprecated', 'Deprecated')], default='planned', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='complianceassessment',
            name='version',
            field=models.CharField(blank=True, default='1.0', help_text='Version of the compliance assessment (eg. 1.0, 2.0, etc.)', max_length=100, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='copyright',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='packager',
            field=models.CharField(blank=True, default='', help_text='Packager of the library', max_length=100, verbose_name='Packager'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='loadedlibrary',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_reference',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Internal reference'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='category',
            field=models.CharField(blank=True, choices=[('policy', 'Policy'), ('process', 'Process'), ('technical', 'Technical'), ('physical', 'Physical')], default='', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='csf_function',
            field=models.CharField(blank=True, choices=[('govern', 'Govern'), ('identify', 'Identify'), ('protect', 'Protect'), ('detect', 'Detect'), ('respond', 'Respond'), ('recover', 'Recover')], default='', max_length=20, verbose_name='CSF Function'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='referencecontrol',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='requirementassessment',
            name='observation',
            field=models.TextField(blank=True, default='', verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='requirementmapping',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='requirementmapping',
            name='rationale',
            field=models.CharField(blank=True, choices=[('syntactic', 'Syntactic'), ('semantic', 'Semantic'), ('functional', 'Functional')], default='', max_length=20, verbose_name='Rationale'),
        ),
        migrations.AlterField(
            model_name='requirementmappingset',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='requirementmappingset',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirementmappingset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='requirementmappingset',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='requirementmappingset',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='requirementmappingset',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='parent_urn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Parent URN'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='typical_evidence',
            field=models.TextField(blank=True, default='', verbose_name='Typical evidence'),
        ),
        migrations.AlterField(
            model_name='requirementnode',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='riskacceptance',
            name='justification',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('in_review', 'In review'), ('done', 'Done'), ('deprecated', 'Deprecated')], default='planned', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='version',
            field=models.CharField(blank=True, default='1.0', help_text='Version of the compliance assessment (eg. 1.0, 2.0, etc.)', max_length=100, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='riskscenario',
            name='justification',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='copyright',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='packager',
            field=models.CharField(blank=True, default='', help_text='Packager of the library', max_length=100, verbose_name='Packager'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='storedlibrary',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='URN'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='annotation',
            field=models.TextField(blank=True, default='', verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='urn',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='URN'),
        ),
    ]
